### ISSUE TITLE
 Is there anything I need to do before uploading the application to the Landungsbrücken board? Or is there anything I need to change to use the MK20DX256VLL10 chip?

### ISSUE THREAD

**Issue by shmoon-tes** [trinamic/TMC-EvalSystem#18]
i'm engineer in korea. 
I made a custom board based on the Landungsbrücke board.
I downloaded the open source of Landungsbrücke into custom board for testing, but it doesn't work.
In my opinion, if there is a significant difference, Landungsbrücke uses MK20DN512VLL10, and the board I designed uses MK20DX256VLL10.
When the MCU chip of Landungsbrücke, which operates normally, was removed and mounted on a custom board, the board operated normally.
Therefore, there seems to be no problem with the circuit of the custom board.

Q1 : Is there anything I need to do before uploading the application to the Landungsbrücken board?

Q2 :  is there anything I need to change to use the MK20DX256VLL10 chip?

**Comment by trinamic-LH** [comment]
Hello,

from what i can tell, the only difference between the two ICs would be the flash memory.
The MK20DN512VLL10 has 512KB of flash, the MK20DX256VLL10 has 256 KB of flash and 256 KB of FlexNVM.
For programs smaller than 256KB the two ICs should behave the same as far as i can tell.

So you were able to program the Landungsbruecke with the DN chip, resolder the chip to your custom board and run successfully. Programming the DX chip on your custom board did not work. Have you checked, whether you are able to program the DN chip on your custom board?

Regards,
Lenard

**Comment by huskier** [comment]
@shmoon-tes @trinamic-LH We're also interested in this issue. Once we have a customized board with MK20DX256VMC10 (1/4 dimensional size compared to MK20DN512VLL10) chip, after downloading the following bootloader,
"https://www.trinamic.com/fileadmin/assets/Products/Eval_Software/Landungsbruecke_bootloader_v1.0.hex"
the system refuse to run, and the crystal does not work at all.

However, we could make the chip work with the internal crystal. After we designed the board with the exact MK20DN512VLL10, we could make our customized board workable with the TMC-EvalSystem open source program. We guess the issue is rooted in the bootloader. Maybe there are some differences between MK20DN512VLL10 and MK20DX256VMC10, and MK20DX256VLL10.

Could you please open source your bootloader? We are still interested in making our board with the chip MK20DX256VMC10 workable, for the chip size is always attracting us!

**Comment by shmoon-tes** [comment]
Thanks for the reply.
The above problem was solved by modifying the contents of the source file.
However, in order to use the boot loader, I also need to modify the boot loader source.
Can't I get the open source of the bootloader?

**Comment by trinamic-LH** [comment]
Hello,

the bootloader is currently not open-source. We are currently discussing internally, whether we can open-source that for you.

What modifications were needed to switch to the different µC?

Regards,
Lenard

**Comment by shmoon-tes** [comment]
I used MK20DX256VLL10.
I modified the RAM Address in MK20DN512.ld with the help of trinamic TechSupport.

In fact, not only the chip but also the frequency of the crystal are different, and I would like to use another UART communication port for download purposes.

When the board currently under development is completed, it will be applied to our products and used a lot.
 I hope you think positively. Thank you.

**Comment by trinamic-LH** [comment]
Hello,

unfortunately we will not be open-sourcing our bootloader since the bootloader code base is shared for other, non-open-source boards too.

For the Evalsystem you can use the non-bootloader builds (named *_NOBL in the build options) to run directly on the hardware.

Alternatively you could implement a compatible bootloader yourself. Here are some references to get you started on that:

- [An appnote detailing the TMCL bootloader command usage](https://www.trinamic.com/fileadmin/assets/Support/Appnotes/AN022-Bootloader_protocol_Rev2.00.pdf)
- [An open-source implementation in python to upload firmwares using the Trinamic bootloader](https://github.com/trinamic/PyTrinamic/blob/b77230a291f59cf12523e649ff69321c5780d8c4/PyTrinamic/examples/tools/FirmwareUpdate.py)
- [The bootloader entry mechanism in the EvalSystem](https://github.com/trinamic/TMC-EvalSystem/blob/46dcbc9dd33c452ce2f4c45faea9b31f9e003780/tmc/TMCL.c#L419)

Regards,
Lenard

**Comment by trinamic-LH** [comment]
For reference purposes:
The MK20DN512VLL10 has 128KB SRAM, the MK20DX256VLL10 has 64KB SRAM [1].
The SRAM memory mapping is defined as the lower half of the SRAM **ending** on the address 0x1FFFFFFF (the higher half therefore starting at 0x20000000) [2].

For the MK20DN512VLL10 this results in the SRAM region being located at [[0x1FFF0000, 0x20010000](https://github.com/trinamic/TMC-EvalSystem/blob/46dcbc9dd33c452ce2f4c45faea9b31f9e003780/hal/Landungsbruecke/freescale/MK20DN512.ld#L27)).
For the MK20DX256VLL10 this results in the SRAM region being located at [0x1FFF8000, 0x20008000) (only taken from the datasheet, i do not have the hardware to verify).

[1]: [Kinetis K Series Microcontrollers Selector guide by NXP](https://www.nxp.com/docs/en/product-selector-guide/KINETISKMCUSELGD.pdf)
[2]: [NXP K20 Reference document for the MK20DN512VLL10 and MK20DX256VLL10](https://www.nxp.com/docs/en/reference-manual/K20P100M100SF2V2RM.pdf)

**Comment by huskier** [comment]
Anyway, thank you very much. @trinamic-LH

**Comment by huskier** [comment]
>  I modified the RAM Address in MK20DN512.ld with the help of trinamic TechSupport.

@shmoon-tes Could you please share the modifications of the MK20DN512.ld file to adapt to the chip MK20DX256VLL10? We'd like to follow your pattern to adapt our chip MK20DX256VMC10.

**Comment by huskier** [comment]
>  I modified the RAM Address in MK20DN512.ld with the help of trinamic TechSupport.

@shmoon-tes Could you please share the modifications of the MK20DN512.ld file to adapt to the chip MK20DX256VLL10? We'd like to follow your pattern to adapt our chip MK20DX256VMC10.

**Comment by shmoon-tes** [comment]
@huskier
I share the code when I use MK20DX256VLL10.

Please delete all existing files before building.


/* Highest address of the user mode stack */
_estack = 0x20008000;    /* end of SRAM */
__SP_INIT = _estack;

/* Generate a link error if heap and stack don't fit into RAM */
__heap_size = 0x400;				/* required amount of heap  */
__stack_size = 0x400; 				/* required amount of stack */

/* Specify the memory areas */
MEMORY
{
  m_interrupts	(rx) : ORIGIN = 0x00000000, LENGTH = 0x1BC
  m_cfmprotrom 	(rx) : ORIGIN = 0x00000400, LENGTH = 0x10
  m_text 		(rx) : ORIGIN = 0x00000410, LENGTH = 512K-0x410
  m_data 	   (rwx) : ORIGIN = 0x1FFF8000, LENGTH = 64K		/* SRAM */
}

**Comment by huskier** [comment]
@shmoon-tes  thank you for sharing the code. One more question:
Don't we neet to change the line:

`m_text (rx) : ORIGIN = 0x00000410, LENGTH = 512K-0x410
`

From our understanding, for MK20DN512VLL10, it should be 512K; but for MK20DX256VLL10, we think it should be 256K? Are we right? Does it matter for this line of code?

**Comment by trinamic-LH** [comment]
@huskier For MK20DN512VLL10 the size of 512K is correct.
For the MK20DX256VLL10 it should be 256K at address 0x00000000 and another 256K at address 0x10000000 [1].

From a quick glance i can't tell whether the FlexNVM or FlexMemory has to be used differently than the normal flash.

[1]: [Section 3.5.1.2 in the Reference Manual](https://www.nxp.com/docs/en/reference-manual/K20P100M100SF2V2RM.pdf)

**Comment by huskier** [comment]
@trinamic-LH Thank you for your reply, Lenard.

We've just tried @shmoon-tes 's code, and it worked for the chip MK20DX256VMC10. 

EUREKA!
